### ISSUE TITLE
USB_A_Female_Vertical_RA_73725-0110BLF.kicad_mod is backwards

### ISSUE THREAD

**Issue by conklech** [Digi-Key/digikey-kicad-library#100]
The courtyard and fab outlines for USB_A_Female_Vertical_RA_73725-0110BLF.kicad_mod are incorrect. Pin 1 is closest to the front of the connector, per the [linked datasheet](http://portal.fciconnect.com/Comergent//fci/drawing/73725.pdf). But the outlines in the footprint extend the other way. Testing with an actual part and PCB (unfortunately...) reveals that the part fits into the footprint backwards. The electrical connection is correct, but the part physically interferes because it extends in the other direction.

![image](https://user-images.githubusercontent.com/573035/57170450-cf90cd80-6dc1-11e9-91e9-054739f271ec.png)

![image](https://user-images.githubusercontent.com/573035/57170428-abcd8780-6dc1-11e9-8df9-7f354bfd7c9a.png)

Either the pads or the outlines should be rotated relative to the other.

**Comment by Reid-L** [comment]
@conklech 
Thank you for the feedback. I will get this fixed as soon as possible.

Thanks,
Reid L

**Comment by Reid-L** [comment]
@conklech 
I have corrected the issue on pull request #104. This should be available on the next build.

Thanks,
Reid L
