### ISSUE TITLE
USB_A_Female_UE27AC54100 length issue

### ISSUE THREAD

**Issue by irbigturtle** [Digi-Key/digikey-kicad-library#109]
Part length on the long end is roughly 19.3mm in footprint, but the actual part length is 13.85mm. 

[https://www.digikey.com/products/en?keywords=UE27AC54100
](https://www.digikey.com/products/en?keywords=UE27AC54100
)

[https://signin.amphenolcanada.com/ProductSearch/drawings/AC/UE27ACX4X0X.pdf](https://signin.amphenolcanada.com/ProductSearch/drawings/AC/UE27ACX4X0X.pdf
)

**Comment by Reid-L** [comment]
@irbigturtle 
Thank you for the feedback. This issue should be fixed on pull request #113 

Thanks,
Reid L
