### ISSUE TITLE
USB_A_Female_UE27AC54100 pin spacing issue

### ISSUE THREAD

**Issue by curiousjp** [Digi-Key/digikey-kicad-library#111]
Hi - new KiCad user here. Not sure if I am misreading something, but I believe there are some very small problems with the pin spacing on this component.

The [Amphenol datasheet](https://signin.amphenolcanada.com/ProductSearch/drawings/AC/UE27ACX4X0X.pdf) for this component shows pin center-to-center horizontal distances (ignoring tolerances for the moment) of:
- Pin 1 to Pin 2: 2.50mm
- Pin 2 to Pin 3: 2.00mm
- Pin 3 to Pin 4: 2.50mm
- SH(L) to Pin 1 / Pin 4 to SH(R): 3.07mm

This gives a nominal center-to-center width between the two shield grounds of 13.14mm, as shown on the datasheet.

Turning to the footprint,
- Pins 1-4 have very slightly different vertical centers.
- The horizontal distance from SH(L) to Pin1 is 2.82mm, not 3.07mm. (SH(L) is centered at -6.57,0.00, Pin 1 at -3.75,-2.71). 
- The horizontal distance from Pin 1 to Pin 2 is 2.5mm, as it should be.
- The horizontal distance from Pin 2 to Pin 3 is 2.5mm, not **2.0mm** as it should be (Pin 2 is centered at -1.25,-2.725, Pin 3 at 1.25,-2.70)
- The horizontal distance from Pin 3 to Pin 4 is 2.5mm, as it should be.
- The horizontal distance from Pin 4 to SH(R) 2.82mm, again not 3.07mm.

Additionally, the pin hole diameters are slightly different to the specified figure on the data sheet (0.90mm vs 0.92).

This probably still all works fine - the differences are very small. But I thought I better bring it to someone who might know how to fix it's attention!

**Comment by Reid-L** [comment]
@irbigturtle 
Thank you for the feedback. This issue should be fixed on pull request #113 

Thanks,
Reid L
