### ISSUE TITLE
Footprint Tweak U.FL_Hirose_U.FL-R-SMT-1_Vertical

### ISSUE THREAD

**Issue by jacky4566** [Digi-Key/digikey-kicad-library#119]
Just a tweak. The U.FL_Hirose_U.FL-R-SMT-1_Vertical footprint should really be centered on the pin. makes it easier to align with other connectors.

**Comment by Reid-L** [comment]
@jacky4566 
Thanks for the feedback. I will take a look at this as soon as possible.

Reid L

**Comment by Reid-L** [comment]
@jacky4566 
This footprint is part of the main KiCad library, not the Digi-Key KiCad Library. I would recommend raising an issue on the main library. https://github.com/KiCad/kicad-footprints 

You could potentially use the Coax_Conn_U.FL in the digikey-footprints library, but be ware the pin numbering is different.

Sorry for the delayed response.

Thanks,
Reid L

**Comment by jacky4566** [comment]
OH. I should have checked that! thanks.
