### ISSUE TITLE
PCB hole size for OSTTC020162 is too small

### ISSUE THREAD

**Issue by goruck** [Digi-Key/digikey-kicad-library#120]
The PCB footprint hole size for OSTTC020162 (dk p/n ED2600-ND) is too small. Its about 0.7 mm but according to the [datasheet](http://www.on-shore.com/wp-content/uploads/OSTTCXX0162.pdf) it should be 1.0mm.

**Comment by Reid-L** [comment]
@goruck 
Thank you for the feedback and pull request. The pull request actually changes the footprint to the incorrect pitched connector. I went ahead and correct the whole series of Terminal_Block_xxx as they were all wrong. Pull request #122 should take care of it.

Thanks,
Reid L

**Comment by goruck** [comment]
Thanks for addressing this.

**Comment by goruck** [comment]
@Reid-L - Quick question. When do the modifications per #122 actually make their way into the digikey-footprints.pretty and digikey-symbol directories? I see the changes made in the src dir. Thanks.

**Comment by bombledmonk** [comment]
Sorry, I forgot to push, I'll do it in the morning.

**Comment by goruck** [comment]
cool. thx.

**Comment by bombledmonk** [comment]
Done.
