### ISSUE TITLE
HowTo import this?

### ISSUE THREAD

**Issue by eabase** [Digi-Key/digikey-kicad-library#124]
How do you actually import this library? 
I'd like to use git clone to ensure my digikey library is always up-to-date.

But there are no instructions on how to import this in such a way that it doesn't get mixed up with the Keycad default libraries. 

Using Windows.

**Comment by jacky4566** [comment]
You can add it the same as any other library. They did change the way it works in version 5.
For symbols:
From Eeschema >Preferences > Manage symbol libraries > click the folder icon and browse to folder.
For footprints:
From Pcbnew > Preferences > Manage footprint libraries > click the folder icon and browse to folder.

**Comment by bombledmonk** [comment]
I guess it would be prudent to put a link to installation instructions in the readme. I'll work on that.

**Comment by Reid-L** [comment]
In the mean time: 

There are several different ways to manage third party libraries like this one. Using git clone is a great way to keep it up to date. 

How you decide to manage the library(s) within KiCad is open to debate, but the way I prefer to use them is to pull them in to the **Project Libraries**, that way they are managed separately from the default libraries, this can be done as such:

1. `git clone https://github.com/Digi-Key/digikey-kicad-library.git` into your preferred directory
2. Open **KiCad**
3. Import the symbols:

    A. Open **Symbol Editor** or **Schematic editor**

    ![image](https://user-images.githubusercontent.com/33766926/62302851-ae7f5d80-b440-11e9-86c9-a16c9bb6aa4e.png)

    B. Click on **Preferences** then on **Manage Symbol Libraries...** 

    ![image](https://user-images.githubusercontent.com/33766926/62298582-e5517580-b438-11e9-8e22-6a2d653e5cff.png) 

    C. Click on the **Project Specific Libraries** tab:
 
    ![image](https://user-images.githubusercontent.com/33766926/62299158-0a92b380-b43a-11e9-8a01-a67fcb112a8e.png)
 
    D. Click on the **Add existing library to table** button: 

    ![image](https://user-images.githubusercontent.com/33766926/62299445-96a4db00-b43a-11e9-8612-485c673360f7.png) 

    E. Navigate to the directory where you cloned the Digi-Key KiCad Library 

    F. Navigate to the **digikey-symbols** folder within **digikey-kicad-library** folder 

    ![image](https://user-images.githubusercontent.com/33766926/62299996-a83ab280-b43b-11e9-99ea-57a4d1fad1ff.png) 

    G. At this point you can add one library at a time or all of the libraries. To add all of the libraries click on any  one of the the libraries and then press `Ctrl+a`. This will select all of the libraries, then click the **Open** button.

    H. You should now see the libraries in the table: 

    ![image](https://user-images.githubusercontent.com/33766926/62300919-3d8a7680-b43d-11e9-97a0-f3b2e7b3b837.png) 

4. Import the footprints(similar process to symbols):
    
   A. Open **Footprint editor** or **PCB Layout**

   ![image](https://user-images.githubusercontent.com/33766926/62302918-d078e000-b440-11e9-9473-fb0b6d11de7f.png)

   B. Click on **Preferences** then on **Manage Footprint Libraries...**

   ![image](https://user-images.githubusercontent.com/33766926/62302988-f1d9cc00-b440-11e9-89b8-9d58d681a33e.png)

   C. Click on the **Project Specific Libraries** tab:

   ![image](https://user-images.githubusercontent.com/33766926/62303231-5dbc3480-b441-11e9-809e-1d643891efb8.png)

    D. Click on the **Add existing library to table** button: 

    ![image](https://user-images.githubusercontent.com/33766926/62304262-3e260b80-b443-11e9-97af-ea587139e999.png)


    E. Navigate to the directory where you cloned the Digi-Key KiCad Library 

    F. Expand the **digikey-kicad-library** folder and select **digikey-footprints.pretty**

    ![image](https://user-images.githubusercontent.com/33766926/62303516-e63ad500-b441-11e9-9d5c-d55209037e87.png)

    G. Click **OK**

    H. The digikey-footprints should now show in your library table

    ![image](https://user-images.githubusercontent.com/33766926/62303746-4a5d9900-b442-11e9-91d1-6532ecde77fb.png)

**Comment by eabase** [comment]
@Reid-L  
Thanks! *That* should be in the README!

**Comment by Reid-L** [comment]
@eabase 
You are welcome! @bombledmonk  added it to the Wiki Page

**Comment by eabase** [comment]
Great!

**Comment by bombledmonk** [comment]
There's a new section in included in the readme.
