### ISSUE TITLE
USB_Mini_B_Female_548190519 footprint is mirrored

### ISSUE THREAD

**Issue by streef** [Digi-Key/digikey-kicad-library#133]
The USB_Mini_B_Female_548190519 footprint, which is a mini-USB through-hole connector, has reverse pad numbering. I found this out the hard way, when I measured -5V instead of +5V on my new board...

**Comment by maker-nathan** [comment]
Confirmed, the previous footprint had the pin numbering backwards. The version created by @dillona is correct. Thank you!

![548190519 Corrected](https://user-images.githubusercontent.com/49135409/100967487-8dbf9000-34ec-11eb-8e9c-785bb90d6ab0.jpg)
