### ISSUE TITLE
Incorrect naming of SOIC-8_W5.3mm

### ISSUE THREAD

**Issue by glominashvili** [Digi-Key/digikey-kicad-library#168]
Hi

Recently I used **SOIC-8_W5.3mm** for atmel attiny85 and the footprint was smaller than the actual chip (**8-lead, 0.208” EIAJ**),
**0.208" is 5.2832mm is ~5.3mm**.
I measured the footprint in KiCad and the width is smaller **~4mm**. I hope **0.150" JEDEC SOIC** will fit it
So maybe it is worth to rename it so other will not make the same mistake?
I'm a beginner, so correct me if I'm missing something.

**Comment by jacky4566** [comment]
AFAIK this library is not being maintained anymore. You would be better off moving to the official KiCad library which had ATTINY85 including the correct footprint. Also you may want to downsize your application for ATTINY25 since that may be the only thing in stock this year.

**Comment by glominashvili** [comment]
Thank you!
