### ISSUE TITLE
TC1047AVNBCT Pinout Incorrect 

### ISSUE THREAD

**Issue by elcritch** [Digi-Key/digikey-kicad-library#95]
The TC1047AVNBCT pinout is incorrect. Pin 1 should be VDD while VSS (GND) is pin 3 according to the [datasheet](http://ww1.microchip.com/downloads/en/DeviceDoc/21498D.pdf).

**Comment by Reid-L** [comment]
@elcritch 

Thank you for the feedback. I will look into this as soon as possible.

Reid L

**Comment by Reid-L** [comment]
@elcritch 

Thank you again for the feedback. My apologies for the slow response. This issue was corrected on pull request #33 

Please make sure you are using the most current version of the library.

Reid L
