### ISSUE TITLE
LTST-C19HE1WT Symbol Wrong

### ISSUE THREAD

**Issue by studio752** [Digi-Key/digikey-kicad-library#96]
dk_LED-Indication-Discrete LTST-C19HE1WT has a symbol for an RGB LED with a common cathode, but according to the datasheet the part has a common anode.

**Comment by Reid-L** [comment]
@studio752 

Thank you for the feedback, I will look into this as soon as possible.

Reid L

**Comment by Reid-L** [comment]
@studio752 

Thank you for the feedback. This has been corrected on pull #99 and will be available in the next build.

Thanks again,
Reid L
